spring.application.name=todolist-spring

# DATABASE
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# EMAIL
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CRON
schedule.time.notify=0 */5 * * * *
schedule.time.update=0 */5 * * * *

# ADMIN
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.username=${ADMIN_USERNAME}

# THYMELEAF
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ACTUATOR
management.endpoints.web.exposure.include=*

# JAVA MELODY
javamelody.enabled=true
javamelody.management-endpoint-monitoring-enabled=true
javamelody.spring-monitoring-enabled=true
javamelody.init-parameters.log=true
javamelody.init-parameters.monitoring-path=/monitoring
javamelody.init-parameters.storage-directory=/tmp/javamelody
javamelody.init-parameters.period-seconds=60
javamelody.init-parameters.sampling-seconds=60